module FacebookWall
  #A Facebook wall post.
  #
  #FacebookWall::Post decorates RSS::Rss::Channel::Item, which means you can easily access all sub-elements of
  #<tt>item</tt>s published in a page's feed.  For example:
  #
  #  post.title        # => A title automatically generated by Facebook
  #  post.link         # => The URL of the wall post
  #  post.description  # => The content of the wall post
  #  post.pubDate      # => The date the post was published
  #  post.author       # => The author of the post
  class Post
    attr_reader :feed_entry

    def initialize(feed_entry)
      @feed_entry = feed_entry
    end

    def method_missing(method_id)  #:nodoc:
      feed_entry.send method_id.id2name
    end
  end
end